server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlite:./base-de-datos/arquitectura.db
    driverClassName: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        ddl-auto: update
  application:
    name: GATEWAY
